// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI7ivYoL4NWXGJvfBz0oG1X_JmVXCLO8M',
    appId: '1:415778807393:web:8e802d78639ee1d6b6d420',
    messagingSenderId: '415778807393',
    projectId: 'zoiao-85aaa',
    authDomain: 'zoiao-85aaa.firebaseapp.com',
    storageBucket: 'zoiao-85aaa.appspot.com',
    measurementId: 'G-B9W4LQ263Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqL-wpsDfQtuUS4QXm_0FqBReeXO0cLaY',
    appId: '1:415778807393:android:fd610a32b451d1f9b6d420',
    messagingSenderId: '415778807393',
    projectId: 'zoiao-85aaa',
    storageBucket: 'zoiao-85aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI6iJnUE86UyvvO8qBdyn8_gFWjZSQl3g',
    appId: '1:415778807393:ios:fe85bc3948c07db2b6d420',
    messagingSenderId: '415778807393',
    projectId: 'zoiao-85aaa',
    storageBucket: 'zoiao-85aaa.appspot.com',
    iosBundleId: 'com.example.zoiao',
  );
}
